server:
  port: 8000 # Port on which the server runs

api:
  base_url: https://consumer-api.development.dev.woltapi.com/home-assignment-api/v1/venues

timeout:
  http_client: 5s # Timeout for HTTP client in seconds
